# Generated by .github/workflows/release.yml for v0.1.0.
class Autoreview < Formula
  desc "Portable, hierarchical, deterministic-first code review CLI"
  homepage "https://github.com/huyz0/autoreview"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/huyz0/autoreview/releases/download/v0.1.0/autoreview-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "d153c490b2b84faad0baa64fe518e3b8c5cc42f42e8228e7a59239a10553e0dc"
    end
    on_intel do
      url "https://github.com/huyz0/autoreview/releases/download/v0.1.0/autoreview-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "1495a3f0bd1ca3583caa1818b7918e2418a6b05542f66dc707379e0159b0cd66"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/huyz0/autoreview/releases/download/v0.1.0/autoreview-v0.1.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "3ed8ddde7814d6f050a9a33856224630de34b7471139b25319655ec1d21c9887"
    end
  end

  def install
    bin.install "autoreview"
  end

  test do
    assert_match "autoreview", shell_output("#{bin}/autoreview --version")
  end
end
